apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-app
  template:
    metadata:
      labels:
        app: hackathon-app
    spec:
      containers: 
      - name: hackathon-app
        image: 458434419861.dkr.ecr.ap-south-1.amazonaws.com/hackathon-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
