name: Build Scan and Deploy CloudShield

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 🔹 Checkout
    - name: Checkout Code
      uses: actions/checkout@v5

    # 🔹 Java Setup
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    # 🔹 Build App
    - name: Build Maven Application
      working-directory: board
      run: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

    # 🔹 Sonar Scan
    - name: SonarQube Scan
      working-directory: board
      run: |
        ./mvnw clean verify sonar:sonar \
        -Dsonar.projectKey=hackathon-app \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # 🔹 AWS Login
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 🔹 ECR Login
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 🔹 Build & Push Docker Image (FIXED)
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

        FULL_IMAGE=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

        echo "Building image: $FULL_IMAGE:$IMAGE_TAG"

        docker buildx build \
          --platform linux/amd64 \
          -t $FULL_IMAGE:$IMAGE_TAG \
          -t $FULL_IMAGE:latest \
          -f board/Dockerfile \
          ./board \
          --push

    # 🔹 Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    # 🔹 Scan Image
    - name: Scan Docker Image
      run: |
        FULL_IMAGE=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
        trivy image --severity HIGH,CRITICAL $FULL_IMAGE:${{ env.IMAGE_TAG }}

    # 🔹 Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $EKS_CLUSTER

    # 🔹 Deploy to EKS
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f board/k8s/deployment.yaml
        kubectl apply -f board/k8s/service.yaml
